class Result
{
    /// <summary>
    /// Processes dynamic array queries and returns the values
    /// obtained from Type 2 queries.
    ///
    /// Query Type 1:
    /// Append y to the sequence at index ((x XOR lastAnswer) % n).
    ///
    /// Query Type 2:
    /// Find the value at index (y % sequence.Count) in the selected
    /// sequence, assign it to lastAnswer, and store it in the result list.
    /// </summary>
    /// <param name="n">
    /// Number of sequences.
    /// </param>
    /// <param name="queries">
    /// List of queries where each query contains
    /// [queryType, x, y].
    /// </param>
    /// <returns>
    /// List containing all values of lastAnswer
    /// produced by Type 2 queries.
    /// </returns>
    public static List<int> dynamicArray(int n, List<List<int>> queries)
    {
        // Create n empty sequences.
        List<List<int>> sequences = new List<List<int>>();

        for (int i = 0; i < n; i++)
        {
            sequences.Add(new List<int>());
        }

        // Stores the last answer generated by Type 2 queries.
        int lastAnswer = 0;

        // Stores all answers to be returned.
        List<int> result = new List<int>();

        // Process each query.
        foreach (List<int> query in queries)
        {
            int type = query[0];
            int x = query[1];
            int y = query[2];

            // Calculate the sequence index.
            int index = (x ^ lastAnswer) % n;

            if (type == 1)
            {
                // Append y to the selected sequence.
                sequences[index].Add(y);
            }
            else if (type == 2)
            {
                // Find the required element and update lastAnswer.
                int valueIndex = y % sequences[index].Count;

                lastAnswer = sequences[index][valueIndex];

                result.Add(lastAnswer);
            }
        }

        return result;
    }
}